# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tvandivi <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/08 18:26:26 by tvandivi          #+#    #+#              #
#    Updated: 2018/11/08 21:34:01 by tvandivi         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC= ft_display_file.c

FLAGS= -Wall -Werror -Wextra

NAME = ft_display_file

all: $(NAME)

$(NAME):
	gcc $(FLAGS) $(SRC) -o $(NAME)
	
clean:
	/bin//rm -f $(NAME)

fclean: clean

re: fclean all
